version: "3.4"

services:
  db:
    image: postgres
    restart: always
    network_mode: "host"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB='postgres'
      - POSTGRES_USER='rd'
      - POSTGRES_PASSWORD='test1234'
  web:
    build: web/
    command: /bin/bash -c "bash runscript.sh"
    volumes:
      - .:/python
    expose:
      - "8000"
    ports:
      - "8000:8000"
    network_mode: "host"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE='postgres'
      - PGUSER='rd'
      - PGPASSWORD='test1234'
  lead:
    build: lead/
    #command: /bin/bash -c "sleep infinity"
    command: /bin/bash -c "sleep 10 && hostname -I && npm run localserve"
    network_mode: "host"
    expose:
      - "1433"
      - "4200"
      - "80"
    ports:
      - "80:80"
      - "1433:1433"
      - "4200:4200"
    depends_on:
      - web

volumes:
  postgres_data:

