version: "3.3"

services:
  db:
    image: postgres
    restart: always
    networks:
      - testing_net
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB='postgres'
      - POSTGRES_USER='rd'
      - POSTGRES_PASSWORD='test1234'
    #command: echo "im in db"
      #command: /bin/bash -c "sleep infinity"
  web:
    build: web/
    command: /bin/bash -c "sleep infinity"
    #command: /bin/bash runscript.sh
    volumes:
      - .:/python
    expose:
      - "8000"
      - "1433"
    ports:
      - "8000:8000"
      - "1433:1433"
    networks:
      - testing_net
    links:
      - db:db
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE='postgres'
      - PGUSER='rd'
      - PGPASSWORD='test1234'

volumes:
  postgres_data:

networks:
  testing_net:
    driver: "bridge"
